config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  # get "restaurants", to: "restaurants#index", as: :index
  # get "restaurants/new", to: "restaurants#new", as: :new_restaurant
  # get "restaurants/:id", to: "restaurants#show", as: :restaurant
  # post "restaurants", to: "restaurants#create"

  resources :restaurants, only: [:index, :new, :show, :create] do
    resources :reviews, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :address, presence: true
  validates :name, presence: true
  validates :category, presence: true
  validates :category, inclusion: { in: ['chinese', 'italian', 'japanese', 'french', 'belgian'] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true
  validates :rating, numericality: { only_integer: true }
  validates :rating, inclusion: { in: (0..5) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.all
  end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render 'restaurants/show', status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
  <h1 class="d-flex justify-content-center mb-4">Restaurants</h1>
  <ul class="text-center list-unstyled">
    <% @restaurants.each do |restaurant| %>
      <li><%= restaurant.name %></li>
      <%= link_to "See datails", restaurant_path(restaurant) %>
    <% end %>
  </ul>
  <div class="text-center mt-4">
    <%= link_to "Add new restaurant", new_restaurant_path, class: 'btn btn-primary' %>
  </div>

app/views/restaurants/new.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category %>
  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<h1 class="d-flex justify-content-center mb-4"><%= @restaurant.name %></h1>
<p class="ms-5">Address: <%= @restaurant.address %></p>
<p class="ms-5">Category: <%= @restaurant.category %></p>
<p class="ms-5">Phone number: <%= @restaurant.phone_number %> </p>

<p class="ms-5"><strong>Reviews</strong></p>
<div class="d-flex inline list-group me-5">
  <ul>
    <% @restaurant.reviews.each do |review| %>
      <li class="list-group-item"><%= review.content %></li>
    <% end %>
  </ul>
</div>
<%= render 'reviews/form' %>
<p><%= link_to 'Back', restaurants_path, class: 'btn btn-dark' %></p>

app/views/reviews/_form.html.erb
<div class="d-flex inline text-center mt-5 ms-5">
  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :rating %>
    <%= f.input :content %>
    <%= f.button :submit, class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/reviews/new.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :rating %>
  <%= f.input :content %>
  <%= f.button :submit %>
<% end %>